<?php

namespace RecruitmentBundle\Repository;

/**
 * CompanyAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
